### ISSUE TITLE
Duplicate Properties Bug/Improvement

### ISSUE THREAD

**Issue by macintoshpie** [occ-data/data-simulator#25]
Currently, if a node in the dictionary references a set of "default properties", and then also explicitly defines those properties itself, the data-simulator is unable to handle the duplication.
It would be nice if the data simulator could recognize the duplicate properties, adopt the values of those explicitly defined on the node, and ignore the default value.
For example,
Entity:
```
"mrna_expression.yaml": {
    ...
    "properties": {
      "error_type": {
        "term": {
        "$ref": "_terms.yaml#/data_file_error_type"
        },
      "enum": [
        "Special Error 1",
        "Special Error 2"
       ]
      },
      "$ref": "_definitions.yaml#/data_file_properties"
    },
    ...
  }
...
```
data_file_properties in _definitions.yaml:
```
data_file_properties:
  ...
  error_type:
    $ref: "#/data_file_error_type"
  ...
```
data_file_error_type in _definitions.yaml:
```
data_file_error_type:
    term:
        $ref: "_terms.yaml#/data_file_error_type"
    enum:
        - file_size
        - file_format
        - md5sum
```
So currently the error_type property would be included twice. The new feature would recognize that error_type is repeated, and choose the one defined within the node (the one with special errors) and ignore the defaults.
